### ISSUE TITLE
Target is missing, currently no records are indexed

### ISSUE THREAD

**Issue by dominique-pfister** [hlxsites/dx-products-newsletter#1]
This line:

https://github.com/hlxsites/dx-products-newsletter/blob/8279d0779ee063e0635b57a66380e1a3424d193a/helix-query.yaml#L10

is currently commented. I suggest to change it to:
```
target: /query-index.json
```
so items get indexed.

**Comment by tripodsan** [comment]
@dylandepass told me, that they don't need indexing. so probably better to remove the `helix-query.yaml` completely.

**Comment by dominique-pfister** [comment]
> @dylandepass told me, that they don't need indexing. so probably better to remove the `helix-query.yaml` completely.

ok, but the indexer keeps getting invoked every minute with 10 indexed records, so we might disable the "once-a-minute" rule for that project.

**Comment by dylandepass** [comment]
@dominique-pfister Apologies, I've removed the `helix-query.yaml` file.
